site_name: Musik- og lydprogrammering 
theme:
  name: material
  language: da
  features:
    - content.code.copy
    - header.autohide
    - navigation.instant
    #- navigation.indexes
    - toc.follow
    - search.suggest
    - navigation.footer
  icon:
    logo: material/waveform
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: green
      accent: lime
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: blue
      accent: indigo

plugins:
  - tags:
      tags_file: index.md
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - attr_list
  - def_list
  - markdown_captions
