site_name: Komposition og lydproduktion med SuperCollider

theme:
  name: material
  language: da
  font:
    text: Source Sans Pro
    code: Source Code Pro
  features:
    - content.code.copy
    - header.autohide
    - navigation.instant
    - toc.follow
    - toc.integrate
    - search.suggest
    - navigation.footer
    - navigation.top
  icon:
    logo: material/waveform
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: blue
      accent: light blue
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: green
      accent: lime

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2022-2025 Anders Eskildsen

plugins:
  - tags
  - search
  - mkdocs-audio
  - bibtex:
      bib_file: "tex/mlprefs.bib"
      csl_file: "docs/stylesheets/apa.csl"
  - privacy
  - caption:
      figure:
        caption_prefix: ''
    
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.blocks.caption
  - admonition
  - attr_list
  - def_list
  - tables
  - footnotes

nav:
  - Forside: index.md
  - Indledning: 00/a-indledning.md
  - 1. Grundlæggende programmering:
    - SuperColliders brugerflade: 01/a-brugerflade.md
    - 01/a-eksekvering.md
    - 01/a-variabler.md
    - 01/a-funktioner.md
    - 01/a-methods.md
    - 01/a-lister.md
    - 01/e-basics.md
    - 01/e-lyd.md
  - 2. En strøm af lyde:
    - Introduktion til Pattern-baseret komposition: 02/a-patterns-intro.md
    - 02/a-random-patterns.md
    - 02/a-pbind.md
    - 02/c-patterns.md
    - 02/e-patterns.md
    - 02/e-generativ-komposition.md
  - 3. Komposition med patterns:
    - Indlejrede patterns: 03/a-indlejring.md
    - 03/a-sammensaetning.md
    - 03/a-patterns-midi.md
    - 03/e-eksempler.md
    - 03/e-minimalisme.md
  - 4. Oscillatorer og modulation:
    - UGens og signalflow: 04/a-ugens.md
    - 04/a-skalering.md
    - 04/c-ugens.md
    - 04/c-ugen-methods.md
    - 04/e-ugens.md
  - 5. Envelopes og SynthDefs:
    - Brug af envelopes: 05/a-envelopes.md
    - 05/a-synthdef.md
    - 05/a-nye-envelopes.md
    - 05/c-synthdef.md
    - 05/e-envelopes.md
  - 6. Klangdannelse med filtre:
    - Filterbaseret klangdannelse: 06/a-filterbaseret-klangdannelse.md
    - 06/a-opskrifter.md
    - 06/a-lilletromme.md
    - 06/a-strenge.md
    - 06/c-filtre.md
    - 06/e-subtraktiv.md
  - 7. Klangdannelse med oscillatorbanke:
    - Oscillatorbanke og multikanalslyd: 07/a-oscillatorbanke.md
    - 07/a-additiv.md
    - 07/a-risset.md
    - 07/a-orgel.md
    - 07/a-vocoder.md
    - 07/e-oscillatorbanke.md
  - 8. Samplebaseret komposition:
    - Afspilning af samples: 08/a-samples.md
    - 08/a-beat.md
    - 08/a-lydcollage.md
    - 08/a-beatslicing.md
    - 08/e-samples.md
    - 08/e-beatslicing.md
  - 9. Klangdannelse med granular syntese:
    - Granular syntese: 09/a-granular.md
    - 09/a-tempo-pitch.md
    - 09/a-tekstur-klangflade.md
    - 09/e-granular.md
  - Diverse ressourcer:
    - Optag lyd fra SuperCollider: 10/a-optag-supercollider.md
    - 10/a-readings.md
    - 10/gratis-samples.md
  - Oversigt: oversigt.md