site_name: Musik- og lydprogrammering 

theme:
  name: material
  language: da
  font:
    text: Source Sans Pro
    code: Source Code Pro
  features:
    - content.code.copy
    - header.autohide
    - navigation.instant
    - toc.follow
    - toc.integrate
    - search.suggest
    - navigation.footer
    - navigation.top
  icon:
    logo: material/waveform
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: blue
      accent: light blue
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: green
      accent: lime

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2022-2025 Anders Eskildsen

plugins:
  - tags:
      tags_file: index.md
  - search
  - mkdocs-audio
  - bibtex:
      bib_file: "tex/mlprefs.bib"
  - privacy
  
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - attr_list
  - def_list
  - tables
  - footnotes

nav:
  - Forside: index.md
  - 1. Grundlæggende programmering:
    - Eksekvering af kildekode: 01/a1-eksekvering.md
    - 01/a2-variabler.md
    - 01/a3-methods.md
    - 01/e1-basics.md
    - 01/e2-lyd.md
  - 2. At generere en strøm af værdier:
    - Introduktion til Patterns: 02/a1-patterns-intro.md
    - 02/a2-random-patterns.md
    - 02/a3-pbind.md
    - 02/c2-patterns.md
    - 02/e1-patterns.md
    - 02/e2-generativ-komposition.md
  - 3. Komposition med patterns:
    - Indlejrede patterns: 03/a1-indlejring.md
    - 03/a2-eksempler.md
    - 03/e1-minimalisme.md
  - 4. Oscillatorer og modulation:
    - Oscillatorer i form af UGens: 04/a1-ugens.md
    - 04/a2-skalering.md
    - 04/c1-ugens.md
    - 04/c2-ugen-methods.md
    - 04/e1-ugens.md
  - 5. Envelopes:
    - Brug af envelopes: 05/a1-envelopes.md
    - 05/a2-synthdef.md
    - 05/a3-nye-envelopes.md
    - 05/c1-synthdef.md
    - 05/e1-envelopes.md
  - 6. Klangdannelse med filtre:
    - Eksempler på subtraktiv syntese: 06/a2-subtraktiv.md
    - 06/a3-lilletromme.md
    - 06/c1-filtre.md
    - 06/e1-subtraktiv.md
  - 7. Klangdannelse med oscillatorbanke:
    - Oscillatorbanke: 07/a1-oscillatorbanke.md
    - 07/a2-additiv.md
    - 07/a3-risset.md
    - 07/a4-orgel.md
    - 07/e1-oscillatorbanke.md
  - 8. Samplemanipulation:
    - Anvendelse af samples: 08/a1-samples.md
    - 08/e1-samples.md
  - 9. Klangdannelse med granular syntese:
    - Granular syntese: 09/a1-granular.md
    - 09/a2-tempo-pitch.md
    - 09/a3-tekstur-klangflade.md
    - 09/e1-granular.md
  - 10. Algoritmisk beatslicing:
    - Beatslicing med patterns: 10/a2-beatslicing.md
    - 10/e1-beatslicing.md
  - Diverse ressourcer:
    - MIDI-output fra SuperCollider: Ressourcer/art1-MIDI-output.md
    - Ressourcer/art2-optag_supercollider.md
    - Ressourcer/gratis-samples.md
    - Ressourcer/lydeksempler.md